config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                                  }
  resources :users
  resources :groups, as: :categories, path: '/categories' do
    resources :expenses
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :icon, presence: true, length: { minimum: 2, maximum: 200 }

  def total_expenses
    expenses.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @expenses = @group.expenses
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.author = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to category_url(@group), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:author_id, :name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, url: '/categories', method: 'post') do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: 'name of category' %>
  </div>

  <div class="field mb-3">
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon, placeholder: 'paste link here' %>
  </div>

  <div class="field mb-3">
    <%= form.submit class: 'brn btn-success text-light p-2' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="d-flex card flex-row" style="height: 5rem;">
  <img src=<%= group.icon %> alt="category icon" class="col-2 img-thumbnail" style=" width: 5rem;">
  <p class="col p-2">
    <strong>Name:</strong>
    <%= group.name %> </br>
    <strong>Total spent:</strong>
    <%= group.total_expenses %>
  </p>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="groups" class="d-flex flex-column m-auto" style="width: 90%;">
  <% @groups.each do |group| %>
    <%= link_to category_path(group), class: 'text-decoration-none', style: 'color: #434b54;' do %>
      <div class="my-2">
        <%= render group %>
      </div>
    <% end %>
  <% end %>
  <%= link_to "New category", new_category_path, class: 'btn btn-success text-light' %>
</div>

app/views/groups/new.html.erb
<section class="mx-4 my-3">
  <h1>New category</h1>

  <%= render "form", group: @group %>

  <br>

  <div>
    <%= link_to "Back to categories", categories_path, class: 'btn btn-secondary' %>
  </div>
</section>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>
<section class="mx-4">
  <div class="d-flex justify-content-between">
    <%= link_to "Back to cateogires", categories_path, class: 'btn btn-secondary mb-3' %>
    <%= button_to 'New expense', new_category_expense_path(@group), method: :get, class: 'btn btn-success text-light mb-3' %>
  </div>
  <div class="d-flex flex-column align-items-center">
    <h3>
      <%= @group.name %>: $<%= @group.total_expenses %>
    </h3>
    <% @expenses.order(created_at: :desc).each do |e| %>
    <div class="container card mb-2">
      <div class="d-flex justify-content-between">
        <div class="mt-2">
          <h5><%= e.name %></h5>
          <p class="mb-0">$ <%= e.amount %></p>
        </div>
        <div class="mt-2">
        <%= button_to "", category_expense_path(category_id: @group.id, expense_id: e.id), params: {expense_id: e.id}, class:'bi bi-trash3 btn btn-danger', method: :delete %>
        </div>
      </div>
      <div class="d-flex justify-content-end">
        <%= e.created_at.strftime('added at: %d %b %Y | %H:%M') %>
      </div>
    </div>
    <% end %>
    <div class="my-2">
      <!-- <%= link_to "Edit this category", edit_category_path(@group), class: 'btn btn-secondary' %> | -->
      <%= button_to "Delete category", category_path(@group), method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</section>