config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                                  }
  resources :users
  resources :groups, as: :categories, path: '/categories' do
    resources :expenses
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @group = Group.find(params[:category_id])
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user
    @group = Group.find(params[:category_id])
    @group_expense = GroupExpense.new(group: @group, expense: @expense)
    @groups = Group.all

    respond_to do |format|
      if @expense.save
        @group_expense.save
        format.html { redirect_to category_url(@group), notice: 'Expense was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense = Expense.find(params[:expense_id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to category_path, notice: 'Expense was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:expense_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: category_expenses_path(@group.id), scope: :expense) do |form| %>
  <% if @expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary my-3' %>
  </div>
<% end %>

app/views/expenses/new.html.erb
<section class="mx-3 my-4">
  <h1>New expense</h1>

  <%= render "form", expense: @group_expense %>

  <br>

  <div>
    <%= link_to "Back to the category", category_path(@group.id) %>
  </div>
</section>